### ISSUE TITLE
Add BUSCO rules

### ISSUE THREAD

**Issue by swarbred** [EI-CoreBioinformatics/minos#17]
@cschu @gemygk 
I would like to get your views on adding rules for BUSCO, running against the genome, final output files and running against the prepare output then creating an external metric based on the output.

We (+others) will always run BUSCO on the final models so for our own convenience it would be good to add this to GMC. It's clear from looking at Koala that a BUSCO "complete" assignment doesn't always indicate the model is really complete (some are clear fragments) but it's a useful qc metric and the relative comparison between the genomic, transcript and protein BUSCO runs  is informative as is comparing the prepare output BUSCO run to the final selected models. I would also like to use the BUSCO assignment in the mikado pick scoring. If a large multiplier is applied this would clearly make the final set of models look better from a BUSCO perspective, which could be viewed as artificial (as we are using busco to select the models and also evaluate them) but it's still a useful option to have if it helps select a more accurate set of models (and for mammalian genomes ~4000 BUSCOs is a big chunk of the geneset. As default we wouldn't apply a large multiplier so it's just another couple of metrics among many. 

The idea would be to

1) Run directly against the genome (BUSCO genome mode)
2) Run against the mikado prepare transcripts AND against the extracted mikado prepare proteins (so another gffread extraction). Create two external metrics based on this output (based on the two runs) e.g. assigning 1 to any complete or duplicated  model and 0.25 to any fragment . One question would be  if it's best to run this against the full set of prepare transcripts and proteins or to split these files first (based on the mikado label) and run against each separately and combine the results. This might depend on the BUSCO --limit setting. We can test this by running BUSCO on the mikado prepare gmc file for koala.
3) Run against the final transcripts and proteins
4) Combine results into a tsv file, plus calculate a few other values based on the results.

 Any issues?

**Comment by swarbred** [comment]
Query @cschu 

Currently if --busco-scoring is not specified then the scroring yaml contains

#external.busco_proteins: {rescaling: max, use_raw: true, multiplier: 3}

i.e. commented out

How does this affect the metrics generation? i.e. are the busco metrics generated but just not used or are they not generated at all? 

I would assume they are always generated irrespective of being used.

**Comment by cschu** [comment]
busco runs should not be affected by not specifying --busco-scoring, that option is only to turn on/off the scoring. Specifying --busco-scoring, however, will force busco protein analysis.
