### ISSUE TITLE
CPC2 download is erratic

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/minos#36]
Two possible solutions here:

1. Use a different mirror from the official, unreliable one. I have cloned the code myself here ago, but this repo seems slightly more up to date:

https://github.com/biocoder/CPC2/

2. Potentially find a different source for this?

**Comment by cschu** [comment]
One could even think of just porting the code (it's not rocket science and terribly written). The current installation requires to port it to python3 anyway and I agree, the download source always seemed to be quite unstable. If I remember correctly, @gemygk was looking (or at least planning to) at alternatives earlier this year (or was that for a different tool?)

**Comment by gemygk** [comment]
@lucventurini 
as @cschu mentioned this is related to https://github.com/EI-CoreBioinformatics/minos/issues/31 and I was working on it and need to look at it again.

**Comment by swarbred** [comment]
CPC2 related it also errors with ambiguity codes that are not N as just discovered via running with the arabidopsis genome. If we stick with CPC2 we might want to clean the provided genome fasta as a preprocessing step (i.e. the equivalent of sed '/^[^>]/ s/[^AGTC]/N/gi' )

**Comment by lucventurini** [comment]
Hi,

any progress on this by any chance? It popped up again today because I am trying to move Minos to GitHub actions and CPC2 is part of the tests.

**Comment by cschu** [comment]
Last time I looked it didn't feel impossible to just port CPC2 to an inhouse version... I didn't do that for time reasons and because I didn't want to deal with the potential license implications*. (I did patch it to Python3 compatibility within the container definition, though). But tbh, one can just rip the functionality out, and put it into an internal script, potentially using scikit to replace the svm part.

*I might have contacted the devs at some point, but if so, there was never any reply.

**Comment by swarbred** [comment]
Hi All,

What are the "realistic" options to resolve this given everyones time / ability to contribute?

**Comment by lucventurini** [comment]
Hi @swarbred 

As I was writing earlier, the quickest and dirtiest would be to change the download location to the GitHub clone:

https://github.com/biocoder/CPC2

Specifically if we want to just download the latest:

`wget --no-check-certificate --content-disposition https://github.com/biocoder/CPC2/tarball/9a2b596`

**Comment by cschu** [comment]
> https://github.com/biocoder/CPC2 

seems like problem solved, no? could also git clone it.

**Comment by lucventurini** [comment]
@swarbred @cschu 

I should have solved this, see #40
