### ISSUE TITLE
Move to GitHub actions

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/minos#38]
Travis is transitioning to a pay-only model and its free version is increasingly slow to use. Moving to GH actions, as in Mikado, would solve the issue.

**Comment by cschu** [comment]
Would be interesting to see if the GH actions tests suffer from the same issues as the Travis ones, namely the failure of all python-based rules.

**Comment by lucventurini** [comment]
The mikado GH actions function well so far - it's worth a shot!

**Comment by lucventurini** [comment]
@cschu 

There is an incogruence at the moment in `minos`.

If I install it using the wheel cycle (`python setup.py bdist_wheel && pip install dist/*whl`) then the contents of the `etc` folder are pushed to the top of the conda enviroment.

If, however, I use the non-wheel installation method (`python setup.py install`) the `etc` folder is put under `lib/python3.{version}/minos/`. This of course breaks the tests.

What would be the expected / desired behaviour?

**Comment by cschu** [comment]
Hi Luca,

Tbh, I'd just do what you did for eiXap. I mean I am not super happy with the etc located inside the package, but it is better than having to "guess-search" where it is...

**Comment by lucventurini** [comment]
Hi @cschu 

Thanks for the feedback. Done and dusted, see PR.
