### ISSUE TITLE
error with collapse_metrics

### ISSUE THREAD

**Issue by swarbred** [EI-CoreBioinformatics/minos#45]
error with collapse_metrics

/ei/.project-scratch/1/1c932027-ee3c-4575-953d-2876fa6fd8fe/CB-GENANNO-436_Koala/minos/MINOS_RUN.minos-1.6.1_run1.err.log

[Thu Feb  4 07:57:22 2021]
Error in rule minos_collapse_metrics:
    jobid: 62
    output: minos-1.6.1_run1/mikado.annotation.collapsed_metrics.tsv, minos-1.6.1_run1/COLLAPSE_METRICS_DONE
    log: minos-1.6.1_run1/logs/minos_run.collapse_metrics.log (check log file(s) for error message)

[Thu Feb  4 07:56:35 2021]
rule minos_collapse_metrics:
    input: minos-1.6.1_run1/mikado.annotation.gff, minos-1.6.1_run1/generate_metrics/metrics_matrix.txt, minos-1.6.1_run1/generate_metrics/metrics_info.txt, minos-1.6.1_run1/kallisto/SRR1106690_2_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1106707_2_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1121764_2_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1122141_2_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1203868_1_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1205138_1_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1205176_1_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1205218_1_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1205222_1_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1205223_1_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1205224_1_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1205998_1_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1207973_2_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1207974_2_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR1207975_2_exp_xx/abundance.tsv, minos-1.6.1_run1/kallisto/SRR3724381_1_exp_xx/abundance.tsv, minos-1.6.1_run1/mikado.annotation.cds.fasta.lengths
    output: minos-1.6.1_run1/mikado.annotation.collapsed_metrics.tsv, minos-1.6.1_run1/COLLAPSE_METRICS_DONE
    log: minos-1.6.1_run1/logs/minos_run.collapse_metrics.log
    jobid: 0
    threads: 8
    resources: mem_mb=32768

[Thu Feb  4 07:57:17 2021]
Error in rule minos_collapse_metrics:
    jobid: 0
    output: minos-1.6.1_run1/mikado.annotation.collapsed_metrics.tsv, minos-1.6.1_run1/COLLAPSE_METRICS_DONE
    log: minos-1.6.1_run1/logs/minos_run.collapse_metrics.log (check log file(s) for error message)

RuleException:
KeyError in line 772 of /ei/software/cb/minos/1.6.1/x86_64/lib/python3.6/site-packages/minos/zzz/minos_run.smk:
'**mikado.phaCin_unsw_v4.1.fa.scaf00001G109.1'**
  File "/ei/software/cb/minos/1.6.1/x86_64/lib/python3.6/site-packages/minos/zzz/minos_run.smk", line 772, in __rule_minos_collapse_metrics
  File "/ei/software/cb/minos/1.6.1/x86_64/lib/python3.6/site-packages/minos/scripts/collapse_metrics.py", line 164, in __init__
  File "/ei/software/cb/minos/1.6.1/x86_64/lib/python3.6/site-packages/minos/scripts/collapse_metrics.py", line 140, in read_metrics
  File "/tgac/software/testing/python_miniconda/4.5.4_py3.6_cs/x86_64/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.

**Comment by cschu** [comment]
Is mikado.phaCin_unsw_v4.1.fa.scaf00001G109.1 a rather short transcript? It might be that it is filtered out in the cds length calculation step. Is this sequence present in the `$prefix.cds.fasta.lengths` in the output?

**Comment by gemygk** [comment]
@cschu its not in the `mikado.annotation.cds.fasta.lengths` file, bit odd

**Comment by gemygk** [comment]
It is classified as ncRNA in `mikado.loci.gff3`, hence no CDS

**Comment by cschu** [comment]
I see.. the desired behaviour would be to not have this present in the collapsed metrics then?

**Comment by lucventurini** [comment]
@cschu 

I think that the desired behaviour would be to include these models but with a CDS length of 0.

**Comment by cschu** [comment]
In that case, just change line 140 in `collapse_metrics.py` to

`tmetrics = TranscriptScores(self.metrics_info, kallisto_score, self.short_cds.get(tdata["id"], 0), **metrics).__dict__` for a quick workaround. 

For robustness' sake, it would be somewhat safer to query `tdata["ftype"] == 'ncrna'` as well.

**Comment by gemygk** [comment]
@cschu I have added ncRNA models to the cds.fasta.lengths files so that the list is complete.

**Comment by cschu** [comment]
Ok, that should also work. Are the cds and cdna sets that you supply disjoint?

**Comment by gemygk** [comment]
They are not disjoint. cds set is a subset of cdna.

**Comment by cschu** [comment]
Ah, my bad I misread the code, sorry. Btw, you can just use sets for the cdna_list and cds_list lists :)
