### ISSUE TITLE
Need help to improve Minos final model based on busco results and oddities

### ISSUE THREAD

**Issue by dadrasarmin** [EI-CoreBioinformatics/minos#58]
Hi,

I used Minos to re-annotate a genome and I can see its positive effect of it on my final model. However, I found out that there are two areas where I can improve the final model.

### Busco
 Based on the Busco results, a model produced by EVM can reach the best for "Fragmented" and "Duplicated" genes. Also, EVM has the closest stats for "best achievable protein Busco count".
When I visualized the models with a genome viewer, I could see that sometimes genes that were predicted to be a gene, are two separated genes in the final Minos model. As an example (Red: Minos, Orange: EVM, Blue: EVM-Mikado, green: reference):
![Screenshot 2022-07-06 at 12 52 25](https://user-images.githubusercontent.com/16366875/177536192-05d716aa-6ca9-4124-8c57-b4e40ad14e67.png)

Which parameter(s) are the most important ones to change in the config file for this situation. I want to try to modify the mikado config file based on `mikado util stats` on the EVM model. However, I am not sure which one affects this specific part.

### Oddities

Based on the oddities, I can see that the final Minos models performs better compared to inputs models except for:

- exon_num > 1
- not is_complete
- not has_start_codon
- not has stop_codon
- selected_cds_fraction <= 0.3
- canonical_intron_proportion != 1
- non_verified_introns_num >= 1
- proportion_verified_introns <= 0.5

In this file, I can see that "high confidence protein-coding" outperforms all other models, however, in the `biotype_conf.summary` I saw that there are fewer genes in the high confidence protein-coding category compared to low confidence:
```
Biotype	Confidence	Gene	Transcript
protein_coding_gene	Low	9790	12297
protein_coding_gene	High	9703	17151
predicted_gene	Low	4503	4572
Total		23996	34020
```

Again, which parameter(s) should I try to optimize to increase `high confidence protein` numbers compared to low confidence proteins? I think this report can improve based on the changes I want to make based on the Busco report, however, if there are more things that affecting this report, I would like to spent some time on them too.

I would highly appreciate your help.

Best,
Armin

**Comment by swarbred** [comment]
@dadrasarmin 

It's difficult to advise in a general way given this will depend on what you have used in the metrics info file, the mikado scoring derived from this and the input models

In the above case I cant really judge from the image what is the "correct" model, one of the two spliced models selected by Minos must have been the highest scoring model in the subloci scoring. My first question would be is the EVM model here actually correct? If that is the desirable model then I would look at the mikado.subloci.scores.tsv and the mikado.subloci.metrics.tsv file and examine the scores of all models that belong to the same sublocus as the desired model. You will find that one of the two models shown in your minos output will have been the highest scoring model at the sublocus level, you can then see what metrics were the main driver for this and potentially adjust in the mikado scoring file and rerun from the pick stage. You can always run mikado pick manually on just this region using the -r option.

Of course any changes you make are applied to all loci i.e you cant just "fix" this one region.

If you have portcullis junctions and not all junctions in the EVM model are supported by a portcullis junction then you will with the config used in the workshop be penalising this model. If your transcriptome data is more limited you might want to penalize less for not having supported junctions (i.e. metrics non_verified_introns_num and proportion_verified_introns_inlocus).

I've never run minos where the final minos models did not have the lowest number of missing BUSCOs, so this really should improve on the EVM run if the multipliers have been set up in the best way for your inputs and data. I suspect there is some tweeking that would improve this but it's hard for me to be specific with the info available.

The classification to high or low confidence is determined by minos_run.run_config.yaml and this section 

```
collapse_metrics_thresholds:
  repeat_associated: '{te_score} >= 0.4'
  predicted_gene: '{hom_acov_score} < 0.3 and {cpc_score} < 0.25'
  hi_confidence: '{classification} == 1 or {busco_score} == 1 or {hom_acov_score}
    >= 0.8 or ({hom_acov_score} >= 0.6 and {transcript_score} >= 0.4)'
  discard: '{busco_score} == 0 and {protein_score} == 0 and {transcript_score} ==
    0 and {hom_acov_score} == 0 and ({expression_score} < 0.3 or {short_cds} == 1)'
```
So you can alter this to lower the bar for what constitutes high confidence, my question would be what is the expected number of genes is it closer to 10,000 or 20,000, what are these low confidence genes, are you happy that these are correct and would regard them as high confidence. For them to be classified as low confidence they likely dont have a high protein homology score, if this is a species that wont have many hits to the homology datasets then you might want to define high confidence differently and update the above collapse_metrics_thresholds.

Minos will select from the input models based on evidence support and to a lesser extent gene model characteristics so what models are available to choose from, the type and extent of evidence and how the metrics are weighted (multiplier) will determine the final set of selected models. There is therefore a lot of scope to make this look "better" or "worse" .

**Comment by dadrasarmin** [comment]
Hi @swarbred,

Thanks a lot for your in-depth explanation. Before I post a question here, I had six models with different input and configurations from minos. However, your instructions helped me to investigate the output files better and optimize the multipliers more efficiently. In fact, I had lots of RNA-Seq data and short assemblies (samples from 38 different growth and stress conditions) and I had to moderate their impact on the pick stage somehow.

After three extra rounds of try and error, I have a model with the highest score in all measurements, including Busco, oddities, AED, etc.

Thanks a lot for your help. I really appreciate it.

Best,
Armin
